// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxsiheluuzihfqbcpsnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4c2loZWx1dXppaGZxYmNwc250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzgzMDYsImV4cCI6MjA2OTIxNDMwNn0.C9kSr9mi6NjOCDRwkJPzHHvyuHSfepknJ08LnJ3ycHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});